'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("filefriendly.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to MIT License
        '''
        '''Copyright (c) 2026 Rob Latour
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        '''
        '''The above copyright notice a [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BothLicenses() As String
            Get
                Return ResourceManager.GetString("BothLicenses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property dock() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("dock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property fflogo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fflogo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overview
        '''
        '''File Friendly works with Microsoft Outlook (R) to file your e-mails exactly where you need them to be, quickly and easily.
        '''
        '''The program scans, organizes, and presents your Outlook e-mails for rapid filing. Related e-mails are automatically chained together and these, as well as individual e-mails, can then be filed in a fraction of the time you are used to.
        '''
        '''Key Features
        '''
        '''- Rapid Email Filing: File emails exactly where you need them, quickly and easily.
        '''- Smart Recommendations: Suggests f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FileFriendly Standard License. 
        ''' 
        '''FileFriendly Copyright © 2009 - 2010 Rob Latour. 
        '''All rights reserved. 
        ''' 
        '''This license applies to the standard-licensed version of FileFriendly. The standard-licensed version of FileFriendly applies to a copy of FileFriendly that has been registered following the payment of a &lt;Price&gt;&lt;/Price&gt; licensing fee. If you have an evaluation version of FileFriendly, see the section titled FileFriendly Evaluation License. 
        ''' 
        '''FileFriendly Standard License 
        ''' 
        '''Your Agreement to  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MITLicense() As String
            Get
                Return ResourceManager.GetString("MITLicense", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
