'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ScanInbox() As Boolean
            Get
                Return CType(Me("ScanInbox"),Boolean)
            End Get
            Set
                Me("ScanInbox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ScanSent() As Boolean
            Get
                Return CType(Me("ScanSent"),Boolean)
            End Get
            Set
                Me("ScanSent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ScanAll() As Boolean
            Get
                Return CType(Me("ScanAll"),Boolean)
            End Get
            Set
                Me("ScanAll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StartDocked() As Boolean
            Get
                Return CType(Me("StartDocked"),Boolean)
            End Get
            Set
                Me("StartDocked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DockRight() As Boolean
            Get
                Return CType(Me("DockRight"),Boolean)
            End Get
            Set
                Me("DockRight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DockLeft() As Boolean
            Get
                Return CType(Me("DockLeft"),Boolean)
            End Get
            Set
                Me("DockLeft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConfirmFile() As Boolean
            Get
                Return CType(Me("ConfirmFile"),Boolean)
            End Get
            Set
                Me("ConfirmFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ConfirmDelete() As Boolean
            Get
                Return CType(Me("ConfirmDelete"),Boolean)
            End Get
            Set
                Me("ConfirmDelete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConfirmUndo() As Boolean
            Get
                Return CType(Me("ConfirmUndo"),Boolean)
            End Get
            Set
                Me("ConfirmUndo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ConfirmExit() As Boolean
            Get
                Return CType(Me("ConfirmExit"),Boolean)
            End Get
            Set
                Me("ConfirmExit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SoundDocking() As Boolean
            Get
                Return CType(Me("SoundDocking"),Boolean)
            End Get
            Set
                Me("SoundDocking") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SoundAlert() As Boolean
            Get
                Return CType(Me("SoundAlert"),Boolean)
            End Get
            Set
                Me("SoundAlert") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConfirmOpen() As Boolean
            Get
                Return CType(Me("ConfirmOpen"),Boolean)
            End Get
            Set
                Me("ConfirmOpen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConfirmHide() As Boolean
            Get
                Return CType(Me("ConfirmHide"),Boolean)
            End Get
            Set
                Me("ConfirmHide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WhenSent() As Boolean
            Get
                Return CType(Me("WhenSent"),Boolean)
            End Get
            Set
                Me("WhenSent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WhenReceived() As Boolean
            Get
                Return CType(Me("WhenReceived"),Boolean)
            End Get
            Set
                Me("WhenReceived") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SoundScanComplete() As Boolean
            Get
                Return CType(Me("SoundScanComplete"),Boolean)
            End Get
            Set
                Me("SoundScanComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ExcludedViewFolders() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ExcludedViewFolders"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ExcludedViewFolders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ExcludedScanFolders() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ExcludedScanFolders"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ExcludedScanFolders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UpgradeNotify() As Boolean
            Get
                Return CType(Me("UpgradeNotify"),Boolean)
            End Get
            Set
                Me("UpgradeNotify") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800")>  _
        Public Property MainWidth() As Double
            Get
                Return CType(Me("MainWidth"),Double)
            End Get
            Set
                Me("MainWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
        Public Property MainHeight() As Double
            Get
                Return CType(Me("MainHeight"),Double)
            End Get
            Set
                Me("MainHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("550")>  _
        Public Property FoldersWidth() As Double
            Get
                Return CType(Me("FoldersWidth"),Double)
            End Get
            Set
                Me("FoldersWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("760")>  _
        Public Property FoldersHeight() As Double
            Get
                Return CType(Me("FoldersHeight"),Double)
            End Get
            Set
                Me("FoldersHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property MainTop() As Double
            Get
                Return CType(Me("MainTop"),Double)
            End Get
            Set
                Me("MainTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("555")>  _
        Public Property MainLeft() As Double
            Get
                Return CType(Me("MainLeft"),Double)
            End Get
            Set
                Me("MainLeft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FoldersTop() As Double
            Get
                Return CType(Me("FoldersTop"),Double)
            End Get
            Set
                Me("FoldersTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FoldersLeft() As Double
            Get
                Return CType(Me("FoldersLeft"),Double)
            End Get
            Set
                Me("FoldersLeft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstRun() As Boolean
            Get
                Return CType(Me("FirstRun"),Boolean)
            End Get
            Set
                Me("FirstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.165")>  _
        Public Property RatioOfRecommendationToProcessingTime() As Double
            Get
                Return CType(Me("RatioOfRecommendationToProcessingTime"),Double)
            End Get
            Set
                Me("RatioOfRecommendationToProcessingTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.2.0.0")>  _
        Public Property ApplicationVersion() As String
            Get
                Return CType(Me("ApplicationVersion"),String)
            End Get
            Set
                Me("ApplicationVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Trial")>  _
        Public Property Registered() As String
            Get
                Return CType(Me("Registered"),String)
            End Get
            Set
                Me("Registered") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Not Yet")>  _
        Public Property Licensing() As String
            Get
                Return CType(Me("Licensing"),String)
            End Get
            Set
                Me("Licensing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NextUpgradeCheckDate() As String
            Get
                Return CType(Me("NextUpgradeCheckDate"),String)
            End Get
            Set
                Me("NextUpgradeCheckDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScreenWidth() As Double
            Get
                Return CType(Me("ScreenWidth"),Double)
            End Get
            Set
                Me("ScreenWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScreenHeight() As Double
            Get
                Return CType(Me("ScreenHeight"),Double)
            End Get
            Set
                Me("ScreenHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoChainSelect() As Boolean
            Get
                Return CType(Me("AutoChainSelect"),Boolean)
            End Get
            Set
                Me("AutoChainSelect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConfirmToggle() As Boolean
            Get
                Return CType(Me("ConfirmToggle"),Boolean)
            End Get
            Set
                Me("ConfirmToggle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property KeepHiddenEmailsHidden() As Boolean
            Get
                Return CType(Me("KeepHiddenEmailsHidden"),Boolean)
            End Get
            Set
                Me("KeepHiddenEmailsHidden") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.filefriendly.My.MySettings
            Get
                Return Global.filefriendly.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
