; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "FileFriendly"
#define MyAppVersion "2.7"
#define MyAppPublisher "Rob Latour"
#define MyAppURL "https://github.com/roblatour/FileFriendly"
#define MyAppExeName "filefriendly.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{122149DC-0621-4478-B0FF-B705171B23F6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={code:GetDefaultDirName}
UninstallDisplayIcon={app}\{#MyAppExeName}

ChangesAssociations=yes
DisableProgramGroupPage=yes
UsePreviousTasks=no
LicenseFile=..\filefriendly\License.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputBaseFilename=FileFriendlySetup
SolidCompression=yes
WizardStyle=modern dynamic windows11
SetupIconFile=..\filefriendly\fflogo.ico


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\filefriendly\bin\x86\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: not Install64BitBuild
Source: "..\filefriendly\bin\x64\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: Install64BitBuild
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  OutlookBitnessKnown: Boolean;
  OutlookIs64Bit: Boolean;
  ArchitecturePage: TInputOptionWizardPage;

function TryGetOutlookPlatform(const RootKey: Integer; var Is64Bit: Boolean): Boolean;
var
  Platform: String;
begin
  Result := False;
  if not RegQueryStringValue(RootKey, 'SOFTWARE\Microsoft\Office\ClickToRun\Configuration', 'Platform', Platform) then
    Exit;

  if CompareText(Platform, 'x64') = 0 then begin
    Is64Bit := True;
    Result := True;
  end else if CompareText(Platform, 'x86') = 0 then begin
    Is64Bit := False;
    Result := True;
  end;
end;

function TryGetOutlookAppPathBitness(var Is64Bit: Boolean): Boolean;
var
  OutlookPath: String;
begin
  Result := False;

  if IsWin64 then begin
    if RegQueryStringValue(HKLM64, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE', '', OutlookPath) then begin
      Is64Bit := True;
      Result := True;
      Exit;
    end;

    if RegQueryStringValue(HKLM32, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE', '', OutlookPath) then begin
      Is64Bit := False;
      Result := True;
      Exit;
    end;
  end else if RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE', '', OutlookPath) then begin
    Is64Bit := False;
    Result := True;
  end;
end;

function DetectOutlookBitness(var Is64Bit: Boolean): Boolean;
begin
  Result := False;

  if IsWin64 then begin
    if TryGetOutlookPlatform(HKLM64, Is64Bit) then begin
      Result := True;
      Exit;
    end;

    if TryGetOutlookPlatform(HKLM32, Is64Bit) then begin
      Result := True;
      Exit;
    end;
  end else if TryGetOutlookPlatform(HKLM, Is64Bit) then begin
    Result := True;
    Exit;
  end;

  Result := TryGetOutlookAppPathBitness(Is64Bit);
end;

function GetInstallDirectory(Is64Bit: Boolean): String;
begin
  if Is64Bit and IsWin64 then
    Result := AddBackslash(ExpandConstant('{pf64}')) + '{#MyAppName}'
  else
    Result := AddBackslash(ExpandConstant('{autopf}')) + '{#MyAppName}';
end;

function GetDefaultDirName(Param: String): String;
var
  Is64Bit: Boolean;
begin
  if DetectOutlookBitness(Is64Bit) then
    Result := GetInstallDirectory(Is64Bit)
  else
    Result := GetInstallDirectory(False);
end;

procedure InitializeWizard;
begin
  OutlookBitnessKnown := DetectOutlookBitness(OutlookIs64Bit);

  if not OutlookBitnessKnown then begin
    ArchitecturePage := CreateInputOptionPage(wpWelcome,
      'Select FileFriendly architecture',
      'Outlook Classic architecture could not be determined',
      'FileFriendly must match the bitness of the installed Outlook Classic application. Select the architecture that matches Outlook Classic.',
      True, True);
    ArchitecturePage.Add('32-bit FileFriendly for 32-bit Outlook Classic');
    ArchitecturePage.Add('64-bit FileFriendly for 64-bit Outlook Classic');
    ArchitecturePage.SelectedValueIndex := 0;
  end;
end;

function Install64BitBuild: Boolean;
begin
  if OutlookBitnessKnown then
    Result := OutlookIs64Bit
  else
    Result := ArchitecturePage.SelectedValueIndex = 1;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;

  if (ArchitecturePage <> nil) and (CurPageID = ArchitecturePage.ID) then
    WizardForm.DirEdit.Text := GetInstallDirectory(Install64BitBuild);
end;

